name: nlp-transfer-learning
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - altair=3.2.0
  - cpuonly=1.0
  - fastai=1.0.57
  - ipykernel=5.1.1
  - ipywidgets=7.5.1
  - jupyterlab=1.0.5
  - jupytext=1.2.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=6.0.0
  - pip=19.1.1
  - python=3.6.*
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - scikit-learn=0.21.2
  - torchvision=0.4.0
  - vega_datasets=0.7.0
  - pip:
    - dataclasses==0.6
    - gpustat==0.6.0

